  docker:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    needs: test  # Depende do job de testes ser concluído com sucesso
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub (opcional)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build Docker image
      run: |
        docker build -t hello-ci-cd .
    
    - name: Test Docker image
      run: |
        docker run --rm hello-ci-cd
        docker run --rm hello-ci-cd --add 5 3
        docker run --rm hello-ci-cd --fact 6
    
    - name: Push to Registry (opcional)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: |
        docker tag hello-ci-cd your-registry/hello-ci-cd:${{ github.ref_name }}
        docker push your-registry/hello-ci-cd:${{ github.ref_name }}
