name: Executar Testes em Todas as Branches

on:
  push:
    branches: '**'  # Executa em qualquer branch
  pull_request:
    branches: '**'  # Executa em PRs de qualquer branch

jobs:
  test:
    name: Executar Testes
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Executar testes
      run: |
        python hello.py --test
