name: CI/CD para Todas as Branches

on:
  push:
    branches: '**'  # Executa em qualquer branch
  pull_request:
    branches: '**'  # Executa em PRs de qualquer branch

jobs:
  test:
    name: Testar Aplicação
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Rodar testes
      run: |
        python hello.py --test

  notify:
    name: Notificar Discord
    needs: test
    runs-on: ubuntu-latest
    if: always()  # Executa mesmo se os testes falharem
    
    steps:
    - name: Enviar notificação
      uses: Ilshidur/action-discord@v1.3.0
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: "Status do CI/CD (${{ github.ref_name }})"
        description: |
          **Repositório**: ${{ github.repository }}
          **Branch**: ${{ github.ref_name }}
          **Status**: ${{ job.status }}
          **Commit**: [${{
github.sha | slice(0,7) }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          **Execução**: [#${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        color: ${{ job.status == 'success' && '65280' || '16711680' }}
        username: "GitHub Actions Bot"
